version: "3"

tasks:
  react-vite:web:
    dir: ./apps/react-vite
    cmd: bun run dev

  react-vite:web:build:
    dir: ./apps/react-vite
    cmd: bun run build

  react-ionic-vite:web:
    dir: ./apps/react-ionic-vite
    cmd: bun run dev

  react-ionic-vite:add:android:
    dir: ./packages/react-ionic-vite-src
    prompt: "Are you sure you want to add android?"
    cmd: bun run cap add android

  react-ionic-vite:add:ios:
    dir: ./packages/react-ionic-vite-src
    prompt: "Are you sure you want to add ios?"
    cmd: bun run cap add ios

  react-ionic-vite:android:
    cmds:
      - bun run --cwd ./apps/react-ionic-vite build
      - defer: bun run --cwd ./packages/react-ionic-vite-src bun run cap run android
      - task: react-ionic-vite:add:android

  react-ionic-vite:ios:
    cmds:
      - bun run --cwd ./apps/react-ionic-vite build
      - defer: bun run --cwd ./packages/react-ionic-vite-src bun run cap run ios
      - task: react-ionic-vite:add:ios

  react-native:web:
    dir: ./apps/react-native
    cmd: bun run web

  react-native:android:
    dir: ./apps/react-native
    cmd: bun run android

  react-native:android:build:
    dir: ./apps/react-native
    cmd: bun run android:build

  react-native:ios:
    dir: ./apps/react-native
    cmd: bun run ios

  react-native:ios:build:
    dir: ./apps/react-native
    cmd: bun run ios:build

  nest:start:
    dir: ./packages/nest-src
    cmd: bun run nest start

  nest:build:
    dir: ./packages/nest-src
    cmd: bun run nest build

  nest:watch:
    dir: ./packages/nest-src
    cmd: bun run nest start --watch

  nest:watch:debug:
    dir: ./packages/nest-src
    cmd: bun run nest start --watch --debug

  nest:test:
    dir: ./apps/nest
    cmd: bun run test

  nest:test:watch:
    dir: ./apps/nest
    cmd: bun run test:watch

  nest:test:cov:
    dir: ./apps/nest
    cmd: bun run test:cov

  nest:test:debug:
    dir: ./apps/nest
    cmd: bun run test:debug

  nest:test:e2e:
    dir: ./apps/nest
    cmd: bun run test:e2e

  nest:orm:
    dir: ./packages/nest-src
    cmds:
      # - bun run prisma init --datasource-provider sqlite --output ./generated/prisma
      - bun run prisma generate
      - bun run prisma migrate dev --name init

  cleanup:
    cmds:
      - rm -rf ./packages/react-vite-src/node_modules
      - rm -rf ./packages/react-ionic-vite-src/node_modules
      - rm -rf ./packages/react-native-src/node_modules
      - rm -rf ./packages/nest-src/node_modules
      - rm -rf ./apps/react-vite/node_modules
      - rm -rf ./apps/react-vite/dist
      - rm -rf ./apps/react-ionic-vite/node_modules
      - rm -rf ./apps/react-ionic-vite/dist
      - rm -rf ./apps/react-native/node_modules
      - rm -rf ./apps/nest/node_modules
      - rm -rf ./apps/nest/dist
      - rm -rf ./deps/react-vite/node_modules
      - rm -rf ./deps/react-ionic-vite/node_modules
      - rm -rf ./deps/react-native/node_modules
      - rm -rf ./deps/nest/node_modules
      - rm -rf ./deps/prisma/node_modules
      - rm -rf ./node_modules

  setup:
    cmds:
      - bun i

      - cp -rf ./packages/react-vite-src/node_modules/@deps/react-vite/node_modules/* ./packages/react-vite-src/node_modules
      - cp -rf ./packages/react-vite-src/node_modules/@deps/react-vite/node_modules/.bin ./packages/react-vite-src/node_modules

      - cp -rf ./packages/nest-src/node_modules/@deps/nest/node_modules/* ./packages/nest-src/node_modules
      - cp -rf ./packages/nest-src/node_modules/@deps/nest/node_modules/.bin ./packages/nest-src/node_modules

      - cp -rf ./packages/nest-src/node_modules/@deps/orm/node_modules/* ./packages/nest-src/node_modules
      - cp -rf ./packages/nest-src/node_modules/@deps/orm/node_modules/.bin ./packages/nest-src/node_modules

      - cp -rf ./packages/react-ionic-vite-src/node_modules/@deps/react-ionic-vite/node_modules/* ./packages/react-ionic-vite-src/node_modules
      - cp -rf ./packages/react-ionic-vite-src/node_modules/@deps/react-ionic-vite/node_modules/.bin ./packages/react-ionic-vite-src/node_modules

      - cp -rf ./packages/react-native-src/node_modules/@deps/react-native/node_modules/* ./packages/react-native-src/node_modules
      - cp -rf ./packages/react-native-src/node_modules/@deps/react-native/node_modules/.bin ./packages/react-native-src/node_modules

      - cp -rf ./apps/react-vite/node_modules/@deps/react-vite/node_modules/* ./apps/react-vite/node_modules
      - cp -rf ./apps/react-vite/node_modules/@deps/react-vite/node_modules/.bin ./apps/react-vite/node_modules

      - cp -rf ./apps/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/* ./apps/react-ionic-vite/node_modules
      - cp -rf ./apps/react-ionic-vite/node_modules/@deps/react-ionic-vite/node_modules/.bin ./apps/react-ionic-vite/node_modules

      - cp -rf ./apps/nest/node_modules/@deps/nest/node_modules/* ./apps/nest/node_modules
      - cp -rf ./apps/nest/node_modules/@deps/nest/node_modules/.bin ./apps/nest/node_modules

      - cp -rf ./apps/nest/node_modules/@deps/orm/node_modules/* ./apps/nest/node_modules
      - cp -rf ./apps/nest/node_modules/@deps/orm/node_modules/.bin ./apps/nest/node_modules

      - cp -rf ./apps/react-vite/node_modules/@packages/react-vite-src/node_modules/* ./apps/react-vite/node_modules
      - cp -rf ./apps/react-vite/node_modules/@packages/react-vite-src/node_modules/.bin ./apps/react-vite/node_modules

      - cp -rf ./apps/react-ionic-vite/node_modules/@packages/react-ionic-vite-src/node_modules/* ./apps/react-ionic-vite/node_modules
      - cp -rf ./apps/react-ionic-vite/node_modules/@packages/react-ionic-vite-src/node_modules/.bin ./apps/react-ionic-vite/node_modules

      - cp -rf ./apps/react-native/node_modules/@packages/react-native-src/node_modules/* ./apps/react-native/node_modules
      - cp -rf ./apps/react-native/node_modules/@packages/react-native-src/node_modules/.bin ./apps/react-native/node_modules

      - cp -rf ./apps/nest/node_modules/@packages/nest-src/node_modules/* ./apps/nest/node_modules
      - cp -rf ./apps/nest/node_modules/@packages/nest-src/node_modules/.bin ./apps/nest/node_modules
