# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  web:
    dir: ../../core/react-vite
    cmd: bun vite

  web:build:
    dir: ../../core/react-vite
    cmds:
      - tsc -b
      - bun vite build
