# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    dir: ../../core/react-electron-vite
    cmd: bun electron-vite dev -- --no-sandbox

  build:
    dir: ../../core/react-electron-vite
    cmds:
      - tsc --composite false
      - bun electron-vite build

  postinstall:
    dir: ../../core/react-electron-vite
    cmd: bun electron-builder install-app-deps

  build:unpack:
    dir: ../../core/react-electron-vite
    cmds:
      - task: build
      - cmd: bun electron-builder --dir

  build:linux:
    dir: ../../core/react-electron-vite
    cmds:
      - task: build
      - cmd: bun electron-builder --linux

  build:win:
    dir: ../../core/react-electron-vite
    cmds:
      - task: build
      - cmd: bun electron-builder --win

  build:mac:
    dir: ../../core/react-electron-vite
    cmds:
      - task: build
      - cmd: bun electron-builder --mac
