# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

env:
  NODE_ENV: development

tasks:
  start:
    dotenv:
      - .env
    dir: ../../internal/nest-src
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start

  build:
    dir: ../../internal/nest-src
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest build

  start:watch:
    dir: ../../internal/nest-src
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start --watch

  start:watch:debug:
    dir: ../../internal/nest-src
    cmds:
      - echo "[NODE_ENV=$NODE_ENV]"
      - NODE_ENV=$NODE_ENV && bun nest start --watch --debug

  orm:init:
    dir: ../../internal/nest-src
    cmds:
      # - bun run prisma init --datasource-provider postgresql --output ./generated/prisma
      - bun prisma generate
      - bun prisma migrate dev --name init

  orm:deploy:
    dir: ../../internal/nest-src
    cmds:
      - task: orm:init
      - bun prisma migrate deploy
      - bun prisma db push
